import { Product, ProductCategory } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Espresso',
    description: 'Rich and bold espresso shot with perfect crema',
    price: 25,
    image: 'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=400',
    category: ProductCategory.COFFEE,
    ingredients: ['Espresso beans', 'Water'],
    nutritionalInfo: {
      calories: 5,
      fat: 0,
      carbs: 1,
      protein: 0,
      sugar: 0,
      caffeine: 63,
    },
    availability: true,
    rating: 4.8,
    reviewCount: 124,
    size: [
      { name: 'Single', price: 25, calories: 5 },
      { name: 'Double', price: 35, calories: 10 },
    ],
  },
  {
    id: '2',
    name: 'Cappuccino',
    description: 'Perfect balance of espresso, steamed milk, and foam',
    price: 35,
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400',
    category: ProductCategory.COFFEE,
    ingredients: ['Espresso', 'Steamed milk', 'Milk foam'],
    nutritionalInfo: {
      calories: 120,
      fat: 4,
      carbs: 12,
      protein: 6,
      sugar: 10,
      caffeine: 63,
    },
    availability: true,
    rating: 4.7,
    reviewCount: 89,
    size: [
      { name: 'Small', price: 35, calories: 120 },
      { name: 'Medium', price: 42, calories: 150 },
      { name: 'Large', price: 48, calories: 180 },
    ],
  },
  {
    id: '3',
    name: 'Latte',
    description: 'Smooth espresso with steamed milk and light foam',
    price: 38,
    image: 'https://images.unsplash.com/photo-1561882468-9110e03e0f78?w=400',
    category: ProductCategory.COFFEE,
    ingredients: ['Espresso', 'Steamed milk', 'Light foam'],
    nutritionalInfo: {
      calories: 150,
      fat: 6,
      carbs: 15,
      protein: 8,
      sugar: 14,
      caffeine: 63,
    },
    availability: true,
    rating: 4.6,
    reviewCount: 156,
    size: [
      { name: 'Small', price: 38, calories: 150 },
      { name: 'Medium', price: 45, calories: 190 },
      { name: 'Large', price: 52, calories: 230 },
    ],
  },
  {
    id: '4',
    name: 'Americano',
    description: 'Espresso shots with hot water for a clean, bold taste',
    price: 28,
    image: 'https://images.unsplash.com/photo-1497636577773-f1231844b336?w=400',
    category: ProductCategory.COFFEE,
    ingredients: ['Espresso', 'Hot water'],
    nutritionalInfo: {
      calories: 10,
      fat: 0,
      carbs: 2,
      protein: 1,
      sugar: 0,
      caffeine: 126,
    },
    availability: true,
    rating: 4.5,
    reviewCount: 78,
    size: [
      { name: 'Small', price: 28, calories: 10 },
      { name: 'Medium', price: 32, calories: 15 },
      { name: 'Large', price: 38, calories: 20 },
    ],
  },
  {
    id: '5',
    name: 'Mocha',
    description: 'Rich chocolate and espresso with steamed milk',
    price: 42,
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400',
    category: ProductCategory.COFFEE,
    ingredients: ['Espresso', 'Chocolate syrup', 'Steamed milk', 'Whipped cream'],
    nutritionalInfo: {
      calories: 290,
      fat: 12,
      carbs: 35,
      protein: 10,
      sugar: 32,
      caffeine: 63,
    },
    availability: true,
    rating: 4.9,
    reviewCount: 203,
    size: [
      { name: 'Small', price: 42, calories: 290 },
      { name: 'Medium', price: 48, calories: 350 },
      { name: 'Large', price: 55, calories: 410 },
    ],
  },
  {
    id: '6',
    name: 'Iced Coffee',
    description: 'Cold brew coffee served over ice',
    price: 32,
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=400',
    category: ProductCategory.COLD_DRINKS,
    ingredients: ['Cold brew coffee', 'Ice'],
    nutritionalInfo: {
      calories: 5,
      fat: 0,
      carbs: 1,
      protein: 0,
      sugar: 0,
      caffeine: 155,
    },
    availability: true,
    rating: 4.4,
    reviewCount: 67,
    size: [
      { name: 'Small', price: 32, calories: 5 },
      { name: 'Medium', price: 38, calories: 8 },
      { name: 'Large', price: 45, calories: 12 },
    ],
  },
  {
    id: '7',
    name: 'Croissant',
    description: 'Buttery, flaky French pastry',
    price: 18,
    image: 'https://images.unsplash.com/photo-1555507036-ab794f4afe5a?w=400',
    category: ProductCategory.PASTRIES,
    ingredients: ['Flour', 'Butter', 'Yeast', 'Salt'],
    nutritionalInfo: {
      calories: 231,
      fat: 12,
      carbs: 26,
      protein: 5,
      sugar: 3,
    },
    availability: true,
    rating: 4.3,
    reviewCount: 45,
  },
  {
    id: '8',
    name: 'Blueberry Muffin',
    description: 'Fresh blueberries in a soft, moist muffin',
    price: 22,
    image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=400',
    category: ProductCategory.PASTRIES,
    ingredients: ['Flour', 'Blueberries', 'Sugar', 'Eggs', 'Butter'],
    nutritionalInfo: {
      calories: 364,
      fat: 15,
      carbs: 54,
      protein: 6,
      sugar: 30,
    },
    availability: true,
    rating: 4.6,
    reviewCount: 92,
  },
]; 